---
name: Deploy
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: iypetrov/go-cr

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
